name: automerge

on:
  push:
    branches:
      - master

jobs:
  build:
    name: automerge
    runs-on: ubuntu-16.04
    steps:
      - name: Action automerge
        uses: saywithu/gitflow-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN
          release: release # release 브랜치 이름
          qa: qa # qa 브랜치 이름
          dev: dev # dev 브랜치 이름
          master: master # master 브랜치 이름
          label: 자동머지 # 풀리퀘스트 라벨
          auto-merge: false # If `true`, will try to automatically merge pull requests. Can also be set to `pull_request_review`, `check_run`, `push`, or a comma-separated combination of these values to only merge when handling the named events.
          require-merge: false # If an attempted merge fails, the action is considered to have failed.
