name: automerge

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    name: Gitflow Automation
    runs-on: ubuntu-latest

    steps:
      - name: automerge
        run: echo Test...
