name: automerge

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    name: Gitflow Automation
    runs-on: ubuntu-latest

    steps:
      - name: automerge1
        run: echo Test11...
      - name: automerge2
        uses: "pascalgn/automerge-action@9d655352861c757731df72b6ac21d65fdf6d92ee"
