name: automerge

on:
  push:
    branches:
      - master

jobs:
  build:
    name: automerge
    runs-on: ubuntu-16.04
    steps:
      - name: Action automerge
        uses: saywithu/gitflow-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # The `GITHUB_TOKEN` secret.
          release: preview # The `release` branch.
          dev: dev # The `dev` branch.
          qa: qa # The `qa` branch.
          master: master # The `master` branch.
          label: 자동머지 # The pull request label.
          auto-merge-branches: release,qa # 여러 브랜치를 자동머지 할 경우에는 브랜치를 컴마 구분한다. 예) release,qa 주의) release: preview와 같을 경우 key이름(release)을 적을것
          auto-merge: true # If `true`, will try to automatically merge pull requests. Can also be set to `pull_request_review`, `check_run`, `push`, or a comma-separated combination of these values to only merge when handling the named events.
          require-merge: false # If an attempted merge fails, the action is considered to have failed.
