name: automerge

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    name: automerge
    runs-on: ubuntu-16.04
    steps:
      - name: Action automerge
        uses: saywithu/gitflow-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN
          release: preview # release 브랜치 이름
          qa: qa # qa 브랜치 이름
          dev: dev # dev 브랜치 이름
          master: master # master 브랜치 이름
          label: 자동머지 # 풀리퀘스트 라벨
          auto-merge-branches: release,qa # 여러 브랜치를 자동머지 할 경우에는 브랜치를 컴마 구분한다. 예) release,qa 주의) release: preview와 같을 경우 key이름(release)을 적을것
          auto-merge: false # If `true`, will try to automatically merge pull requests. Can also be set to `pull_request_review`, `check_run`, `push`, or a comma-separated combination of these values to only merge when handling the named events.
          require-merge: false # If an attempted merge fails, the action is considered to have failed.
